<?php

namespace AppBundle\Repository;

/**
 * CoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursRepository extends \Doctrine\ORM\EntityRepository
{
	public function getOrderCoursList()
	{
		# code...
		return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM AppBundle:Cours c ORDER BY c.dateDebut ASC'
            )
            ->getResult();
	}
}
