<?php

namespace AppBundle\Repository;

/**
 * LeyoroboRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeyoroboRepository extends \Doctrine\ORM\EntityRepository
{
}
