<?php

namespace AppBundle\Repository;

/**
 * ParticipationsCoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationsCoursRepository extends \Doctrine\ORM\EntityRepository
{
	public function getParticipants($idCours)
	{
		# code...
		return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:ParticipationsCours p Where p.cours = :idc'
            )
            ->setParameter('idc', $idCours)
            ->getResult();
	}

	public function setPresent($var1, $var2)
	{
		# code...

		$get = $this->getEntityManager()
            ->createQuery(
                'SELECT p.id, p.presence FROM AppBundle:ParticipationsCours p Where p.id = :v1'
            )
            ->setParameter('v1', $var1)
            ->getOneOrNullResult();


        $this->getEntityManager()
            ->createQuery(
                'UPDATE AppBundle:ParticipationsCours p SET p.presence = :val WHERE p.id = :v1'
            )
            ->setParameter('v1', $var1)
            ->setParameter('val', !$get['presence'])
            ->getResult();

		return !$get['presence'];
	}
}
